// <auto-generated />
namespace MovieTrackingWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ReviewChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReviewChange));
        
        string IMigrationMetadata.Id
        {
            get { return "202103050407252_ReviewChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
